### ISSUE TITLE
Plugin Config Acknowledgement and Error Checking

### ISSUE THREAD

**Issue by drardin** [villanovachile/blocks-for-discogs#4]
A success or failure error should be returned after entering Discog username, API token and clicking the option to save the config. 

Perhaps the pair can be used to determine if a collection is empty and return a config status.

**Comment by villanovachile** [comment]
Thanks for the suggestion! Added in [25e0e22](https://github.com/villanovachile/blocks-for-discogs/commit/25e0e22a3d1cc58f2590ae222273e0c4d0fd65ba)
