### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by Fafnyir** [villanovachile/blocks-for-discogs#5]
**Describe the bug**

**To Reproduce**
Attempt tp login with a username the\at contains a _

**Expected behavior**
Login

But it removes the underscores and attempts to login. But the username then is incorrect.

**Comment by ash1eygrace** [comment]
Hey, thanks for reporting this issue.

 I just did some testing, and if my understanding is correct, when you enter in your username via the Blocks for Discogs and click Save Changes, it strips out the underscore of your username? 

If so, I think I see the issue in the [310 in of the drbfd_blocks_for_discogs_validate_username function](https://github.com/villanovachile/blocks-for-discogs/blob/3f4b8b12f6a74e20b9a7f39de000df1077843b29/blocks-for-discogs.php#L310). We need to include `_` and possibly `-` in the regex. 

We'll work on getting this fixed this weekend! Thank you for taking the time to report it.
